# ***************** NSO container configurations ***************** #
nso:
  container_name: nso-pipeline
  image: cisco-nso-prod:6.4
  username: admin
  password: admin
  http_port: 8080
  https_port: 8888
  cli_port: 1024

# ***************** URLs for downloading our NEDs ***************** #
# Preferably from an Artifact Server - In this case we are using a public GitHub repository with free trial NEDs as releases #
downloads:
  - https://github.com/ponchotitlan/dummy_artefact_repository/releases/download/iosxr/ncs-6.4-cisco-iosxr-7.61.tar.gz

# ***************** Netsims to be used in the tests of this pipeline ***************** #
# The NED names must match the folders after extracting from the tar files downloaded #
netsims:
  cisco-iosxr-cli-7.61:
    - ciscolive-iosxr-dummy-01
    - ciscolive-iosxr-dummy-02

# ***************** Docker network name prefix ***************** #
container_network: net